steps:
  - block: "Enter Worker Name"
    blocked_state: running
    fields:
      - text: "Worker Name"
        key: "WORKER_NAME"
        required: true
        hint: "Enter the name of the worker"

  - label: "Publish Worker"
    command: |
      set -x
      chmod +x scripts/publish_worker.py
      ls -l scripts
      python3 scripts/publish_worker.py

    
  # - label: ":python: Get Worker Version IDs"
  #   command: |
  #     python3 scripts/get_versions.py
  #   env:
  #     WORKER_NAME: "${WORKER_NAME}"  # Pass worker name from the field
