steps:
  - label: "Get Secrets"
    command: |
      export CLOUDFLARE_API_TOKEN=$(buildkite-agent secret get CLOUDFLARE_API_TOKEN)
      export CLOUDFLARE_ACCOUNT_ID=$(buildkite-agent secret get CLOUDFLARE_ACCOUNT_ID)

      echo $(buildkite-agent secret get CLOUDFLARE_ACCOUNT_ID)
    env:
      CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
      CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    
  - block: "Enter Worker Name"
    blocked_state: running
    fields:
      - text: "Worker Name"
        key: "WORKER_NAME"
        required: true
        hint: "Enter the name of the worker"

  - label: "Publish Worker"
    command: |
      export WORKER_NAME=${WORKER_NAME}
      python3 scripts/publish_worker.py
    env:
      WORKER_NAME: $WORKER_NAME

    
  # - label: ":python: Get Worker Version IDs"
  #   command: |
  #     python3 scripts/get_versions.py
  #   env:
  #     WORKER_NAME: "${WORKER_NAME}"  # Pass worker name from the field
