steps:
  - label: ":nodejs: Test All Workers (Main Branch)"
    command: |
      ./scripts/test_all.sh

  # - wait: ~

  # - trigger: "cloudflare-worker-canary-ramp"
  #   label: ":rocket: Trigger Deployment Pipeline"
  #   build:
  #     message: "Tests passed, triggering deployment"
  #     commit: "${BUILDKITE_COMMIT}"
  #     branch: "${BUILDKITE_BRANCH}"