steps:
  - label: ":nodejs: Test All Workers (Main Branch)"
    command: |
      ./scripts/test_all.sh
    plugins:
    - docker-compose#v4.15.0:
        run: worker-test
        config: docker/docker-compose.test.yml

  - wait: ~

  - trigger: "cloudflare-worker-deploy-workflow"
    label: ":rocket: Trigger Deployment Pipeline"
    build:
      message: "Tests passed, triggering deployment"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"