steps:
  - label: ":nodejs: Test All Workers (Main Branch)"
    command: |
      echo "Setting up Node.js environment..."
      echo "Running tests for all workers..."
      
      dirs=$(find . -maxdepth 1 -type d -name '*worker*')

      for dir in $dirs; do
        echo "Testing worker: $dir"
        cd $dir
        npm ci
        npm test
        cd ..
      done