steps:
  - label: ":nodejs: Test All Workers (Main Branch)"
    command: |
      echo "Setting up Node.js environment..."
      
      dirs=$(find . -maxdepth 1 -type d -name '*worker*')

      echo $dirs
      echo "Running tests for all workers ${dirs}"

      for dir in $dirs; do
        echo "Testing worker: $dir"
        cd $dir
        npm ci
        npm test
        cd ..
      done

  - wait: ~

  - trigger: "cloudflare-worker-canary-ramp"
    label: ":rocket: Trigger Deployment Pipeline"
    build:
      message: "Tests passed, triggering deployment"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"